apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nodejs-app
  namespace: staging
  labels:
    app: simple-nodejs-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-nodejs-app
  template:
    metadata:
      labels:
        app: simple-nodejs-app
    spec:
      containers:
      - name: simple-nodejs-app
        image: your-dockerhub-username/simple-nodejs-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"
